[tool.poetry]
name = "django-jukebox"
version = "0.1.0"
description = ""
authors = ["Paige <paige@paige.bio>"]
readme = "README.md"
packages = [{include = "django_jukebox", from = "src"},  {include = "django_jukebox_host", from = "src"}, {include = "django_jukebox_manage", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.7"
django = "^4.1.7"
django-extensions = "^3.2.1"
mutagen = "^1.46.0"
python-daemon = "^2.3.2"
django-otp = "^1.1.4"
simplejson = "^3.18.3"
python-ldap = "^3.4.3"
django-bower = "^5.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
autopep8 = "^2.0.1"
ipython = "^8.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
django_jukebox_admin = "django_jukebox_manage:main"
django_jukebox_daemon = "django_jukebox.juke_daemon:daemon_loop"